version: "3"

services:
  db:
    image: "postgres:latest"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5050:5432"
    environment:
      - POSTGRES_USER=mipt
      - POSTGRES_PASSWORD=mipt
      - POSTGRESQL_PASSWORD=mipt
